### ISSUE TITLE
Can you provide some screenshot?

### ISSUE THREAD

**Issue by mygithubthrowaway** [AlexandreDey/ContainerBox#11]
as question

**Comment by AlexandreDey** [comment]
Hi,

Sorry for the delay, I was really busy the past few weeks. I can provide screenshots, what do you want to see more specifically ?

**Comment by mygithubthrowaway** [comment]
No problem obv. 
Maybe some DE working, or gui application? it's always nice to see

**Comment by AlexandreDey** [comment]
README updated with two screenshots, tell me if you want more :)

**Comment by mygithubthrowaway** [comment]
Thanks! :)
