### ISSUE TITLE
Running ContainerBox in SNAP LXD

### ISSUE THREAD

**Issue by bmullan** [AlexandreDey/ContainerBox#4]
After changing all of the LXC= statements to point to /snap/bin/lxc ContainerBox seems to have installed successfully.

Then executing:
**$ ContainerBox create -n cn1 -t ubuntu** 

Appears to successfully create the LXC container I named "cn1".   Note I left all other options "defaulted".

The executing ...

$ ContainerBox start -n cn1

Appears to successfully create the LXC container I named "cn1"  but a black box appears on the screen where I guess the containers GUI should be and then I receive the following error messages:

> 1025
> Error: The device doesn't exist
> Device X1025 added to cn1
> Display :1025 socket passed to cn1
> 
> ** (lightdm:178): WARNING **: 16:17:46.401: Failed to get system bus: Could not connect: No such file or directory
> Failed to get D-Bus connection

Brian

**Comment by AlexandreDey** [comment]
Thanks for all the feedback! 
Once the Xephyr window is launched (the black box), could you connect to the container console and run "ls -al /tmp/.X11-unix" just to see if the screen device is truly passed through.
If so, run "lightdm -d" to start the display manager in verbose mode. Also if you can give me the output of the lightdm log file (should be /var/log/lightdm/seat0-something.log), it might help debugging

**Comment by AlexandreDey** [comment]
The new commit solves the problem.

For existing containers, run as root
# rm /usr/share/lightdm/lightdm.conf.d/50-xubuntu-numlock.conf

This removes the faulty lightdm config that prevents it to start

**Comment by bmullan** [comment]
yes that fixes it...
