### ISSUE TITLE
Following README - use of "--x" option fails with "unknown parameter"

### ISSUE THREAD

**Issue by bmullan** [AlexandreDey/ContainerBox#5]
$ **ContainerBox create -n cn1 -t ubuntu -d xfce --x yes**
Unknown parameter '--x' !

**Comment by bmullan** [comment]
FYI...

I am on Ubuntu 18.04

I have installed ContainerBox in an Ubuntu 18.04 KVM VM.

**Comment by bmullan** [comment]
The README says the command option for xpra uses "--x" as a switch
**--x yes/no**                # for for xpra support

But experimenting it looks like perhaps it was changed to:
**--xpra yes/no** 

At least using that in my command line doesn't throw they error about "Unknown Parameter"

**Comment by AlexandreDey** [comment]
Solved it in latest commit. Either use '-x yes' or '--xpra yes'
