### ISSUE TITLE
documentation for use of "ContainerBox config" command

### ISSUE THREAD

**Issue by bmullan** [AlexandreDey/ContainerBox#7]
Environment:

KVM Ubuntu 18.04 virtual machine.

All I saw in the README about the ContainerBox config command was:

> ContainerBox config network|system|shared_folder|sound NAME_OF_CONTAINER(required) [ OPTIONS ]

I did everything up to that point (called my container CN!)

   $ sudo apt install Install lxd xserver-xephyr -y
   $ sudo ./install.sh
   $ ContainerBox create -n CN1 -t ubuntu -d XFCE --x no 
   $ ContainerBox start -n CN1 -m xephyr -f yes

I then found the following somehow:

> ContainerBox config sound CONTAINER_NAME ACTION [OPTIONS]:
> ACTION:
> 	pa_enable: Passthrough host PulseAudio socket to the container (/tmp/pulse_socket)
> 	pa_disable: Remove host PulseAudio socket from the container
> 
> 	snd_enable: Passthrough the sound cards inside container
> 	snd_disable: Remove the sound cards from the container

So I tried to enable SOUND in my CN1 container using the following and got a failure:

**$ ContainerBox config sound cn1 pa_enable**
Failure: Module initialization failed
**setfacl: /home/bmullan/.ContainerBox/cn1-pulse: No such file or directory
Error: Failed to setup device: Source path /home/bmullan/.ContainerBox/cn1-pulse doesn't exist for device pulse**

My Host is an Ubuntu 18.04 and so is CN1.

I don't think I missed any steps... do you have any ideas?

**Comment by AlexandreDey** [comment]
Hmm, your container is called cn1 or CN1 ? It is case sensitive (but I don't think that's the problem)

Other option I see: how are you providing sound to the VM ? Is it from the pulseserver of the host ? If that's the case, then the problem is probably that (it is assumed that the pulse server is running on the machine, so that machine must have it's soundcard)

**Comment by bmullan** [comment]
I can play audio in the VM okay but get that error when I used that
Container box command I posted previously.

Yes the container is actually called "cn1".  I typed it upper case to
highlight it in the email

Brian

On Jul 10, 2018 5:13 AM, "AlexandreDey" <notifications@github.com> wrote:

Hmm, your container is called cn1 or CN1 ? It is case sensitive (but I
don't think that's the problem)

Other option I see: how are you providing sound to the VM ? Is it from the
pulseserver of the host ? If that's the case, then the problem is probably
that (it is assumed that the pulse server is running on the machine, so
that machine must have it's soundcard)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AlexandreDey/ContainerBox/issues/7#issuecomment-403755814>,
or mute the thread

**Comment by AlexandreDey** [comment]
Could you show me the output of "ls /dev/snd" inside the VM ?
If there is nothing, there is the problem (no physical soundcard inside the VM).

If there is a soundcard, can you give me the output of "bash -xv /etc/ContainerBox/host/config sound cn1 pa_enable" it should run it line by line

The last possibility I see is that pulseaudio is already configured to use a socket file and it fails because of that

I have tested on a VirtualBox VM too, it seems to work.

**Comment by bmullan** [comment]
In the Host Ubuntu 18.04 VM
*...*
*vm1:~$ ls /dev/snd*
*by-path  controlC0  hwC0D0  pcmC0D0c  pcmC0D0p  seq  timer*

I'll try to get you the output of:

"bash -xv /etc/ContainerBox/host/config sound cn1 pa_enable"

later but I have to take my daughter's dog to the veterinarian now so it
will be a while
before I get back.

brian

**Comment by AlexandreDey** [comment]
Hmm ... is pulseaudio running on the vm ? 
what's the content of "~/.ContainerBox/" ? If the folder does not exist, it might be the problem

**Comment by AlexandreDey** [comment]
The "admin user" error is debian/ubuntu specific (after creating the container, ContainerBox adds a administrator inside the container and by default it is named 'admin'. The problem is that debian-based containers have an admin group by default, which prevent the creation of the user)

Something I forgot to add ... The creation of the .ContainerBox folder inside the home directory (shared_folder does it by default, but not sound). Try creating this folder and see if it solves the problem :)

**Comment by bmullan** [comment]
Alexandre

I will try this but as there is no online documetnation for the
ContainerBox config command...

$ ContainerBox config shared_folder
Configuration directory for shared folder does not exist, creating ...
ContainerBox config shared_folder CONTAINER_NAME ACTION [OPTIONS]:
ACTION:
    list: list folders currently shared with container

    add: share a new folder
        ContainerBox config shared_folder CONTAINER_NAME add SOURCE_FOLDER
CONTAINER_FOLDER_NAME PERMISSIONS

    remove: unshare a folder
        ContainerBox config shared_folder CONTAINER_NAME remove
SOURCE_FOLDER

So I made a guess and did the following command:

$ ContainerBox config shared_folder cn1 add /home/bmullan/.ContainerBox
/home/bmullan/.ContainerBox

and it DOES create the .ContainerBox directory in cn1 under /home/bmullan
but the owner = "nobody" and the group = "nogroup"  ??

Not sure what "permissions" implies and found no way to find out  (assuming
its for normal file permissions??)

Brian

**Comment by bmullan** [comment]
Also this may be a bug... but I removed the shared .ContainerBox directory

$ ContainerBox config shared_folder cn1 remove /home/bmullan/.ContainerBox
Device 3b5d9026d525e47e6ebc7c4c39d46e25 removed from cn1

But decided to check if it really was removed:

$ lxc exec cn1 bash
# cd /home/bmullan

# ls -la
total 36
drwxr-xr-x 4 bmullan bmullan 4096 Jul 11 13:24 .
drwxr-xr-x 4 root    root    4096 Jul 11 12:05 ..
drwxr-xr-x 2 root    root    4096 Jul 11 13:24 .ContainerBox
-rw-r--r-- 1 bmullan bmullan 1600 Jul 11 12:05 .Xdefaults
-rw-r--r-- 1 bmullan bmullan  220 Jul 11 12:05 .bash_logout
-rw-r--r-- 1 bmullan bmullan 3771 Jul 11 12:05 .bashrc
drwxr-xr-x 3 bmullan bmullan 4096 Jul 11 12:05 .config
-rw-r--r-- 1 bmullan bmullan  807 Jul 11 12:05 .profile
-rw-r--r-- 1 bmullan bmullan   14 Jul 11 12:05 .xscreensaver

NOTE: that /home/bmullan (in the container) still has a ".ContainerBox"
directory but now
the Owner = root and the Group = root   ??

Just fyi.

brian

**Comment by bmullan** [comment]
Even tho my previous post showed that removing the shared folder indicates success but the cn1 container /home/bmullan/.ContainerBox was not removed only owner/group changed to root.

I decided to see what happens if I changed the owner/group to "bmullan"

**# chown bmullan:bmullan /home/bmullan/.ContainerBox**

then stop the container to try to enable sound (it appears to add the pulse device to cn1 ? but attempting to "ContainerBox start" cn1 again still emits "errors" (see below).

**$ lxc stop cn1**
**$ ContainerBox config sound cn1 pa_enable**
_24
Device pulse added to cn1_

**$ ContainerBox start -n cn1 -m xephyr -f no**
_cn1 -m xephyr -f no
Xephyr cannot open host display. Is DISPLAY set?
Error: The device doesn't exist
Error: The device doesn't exist
Error: Failed to setup device: Source path /tmp/.X11-unix/X1025 doesn't exist for device X1025
Display :1025 socket passed to cn1_

** (lightdm:178): WARNING **: 13:36:20.465: Failed to get system bus: Could not connect: No such file or directory

**Comment by bmullan** [comment]
Alexandre

In a previous message  you stated:

> Something I forgot to add ... The creation of the .ContainerBox folder inside the home directory (shared_folder does it by default, but not sound). Try creating this folder and see if it solves the problem :)

If that's true shouldn't code be added to the **_ContainerBox config sound_** to "_check_" for the existence of **/home/userID/.ContainerBox** and if it doesn't exist "**create**" it just as the "**_ContainerBox config shared_folder_**" would have ?  

If not the above then at least an *"error"* message telling them to run **ContainerBox config shared_folder** first?

Brian

**Comment by AlexandreDey** [comment]
Brian, 

I will answer tomorrow, sorry not really available at the moment.

Alexandre

**Comment by bmullan** [comment]
nothing urgent Alexandre... thx

**Comment by AlexandreDey** [comment]
More complete documentation is on its way an should arrive as soon as I have time to complete and compile everything ;)

~/.ContainerBox folder is the directory where every user specific files are stored. At first it was only used by "shared_folder" option to store the list of folder the user was sharing with the container. But it is also used by the sound configuration, it just creates the pulse socket inside the directory. I just forgot to check for the creation of the folder in the sound configuration (patch will be commited shortly).


About the DISPLAY error message, it is possible that it's just a synchronisation problem (the display is still being created when CBox tried to pass it through). Gonna look into it to see how I might solve it.

Once you created ~/.ContainerBox folder, were you able to use pa_enable ?

**Comment by bmullan** [comment]
Yes... once ~/.ContainerBox is created it appears I can enable Pulse Audio... However, when I start the container I get several (see below):   _"Error: The device doesn't exist"_

vm1:~$ ContainerBox config sound cn1 pa_enable
23
Device pulse added to cn1
bmullan@bmullan-vm1:~$ ContainerBox start -n cn1 -m xephyr -f no 
cn1 -m xephyr -f no
**_Xephyr cannot open host display. Is DISPLAY set?
Error: The device doesn't exist
Error: The device doesn't exist
Error: Failed to setup device: Source path /tmp/.X11-unix/X1025 doesn't exist for device X1025_**
Display :1025 socket passed to cn1
bmullan@bmullan-vm1:~$

**Comment by AlexandreDey** [comment]
Does the problem still occur after a reboot ?
I will try to see if I can reproduce the problem

**Comment by bmullan** [comment]
yes... I tried a reboot also

**Comment by AlexandreDey** [comment]
Seeing the error message for your problem, it seems that Xephyr cannot find the host display. Are you starting the container from an existing display (it is mandatory)?

**Comment by AlexandreDey** [comment]
Still far from complete and easy to read, but you can now type "ContainerBox config help" to have a list of all possible commands. Also checked for the existence of "~/.ContainerBox" folder

**Comment by bmullan** [comment]
Alexandre

Couple of things...

First a bug I think:

in the VM (not the container)
$ ContainerBox config shared_folder cn1 add ~/.ContainerBox /home/bmullan/.ContainerBox
/bin/grep: /home/bmullan/.ContainerBox/shared_folder/list: No such file or directory
Device 3b5d9026d525e47e6ebc7c4c39d46e25 added to cn1

start & enter container
$ lxc start cn1
bmullan@bmullan-vm1:~$ lxc exec cn1 bash

list all files in /home/bmullan to check for ~/.ContainerBox its there... _but ... its OWNER/GROUP is nobody/nogroup ??_

root@cn1:~# cd /home/bmullan
root@cn1:/home/bmullan# ls -la
total 40
drwxr-xr-x  4 bmullan bmullan 4096 Jul 14 18:10 .
drwxr-xr-x  4 root    root    4096 Jul 14 18:07 ..
**drwxrwxr-x+ 3 nobody  nogroup 4096 Jul 14 18:07 .ContainerBox**
-rw-r--r--  1 bmullan bmullan 1600 Jul 14 18:07 .Xdefaults
-rw-r--r--  1 bmullan bmullan  220 Jul 14 18:07 .bash_logout
-rw-r--r--  1 bmullan bmullan 3771 Jul 14 18:07 .bashrc
drwxr-xr-x  3 bmullan bmullan 4096 Jul 14 18:07 .config
-rw-r--r--  1 bmullan bmullan  807 Jul 14 18:07 .profile
-rw-r--r--  1 bmullan bmullan   14 Jul 14 18:07 .xscreensaver

==================

In the new "ContainerBox config help" I'd suggest inserting an "example use" of each command or command option?

for instance for "ContainerBox config" maybe just show how to share the ~/.ContainerBox directory??

Brian

**Comment by bmullan** [comment]
Making some progress...

I found that during ContainerBox install/config the PULSE_SERVER environment variable never got set for my UserID inside the container CN1.   

I added the following to my **.profile** (inside the container):

**export PULSE_SERVER="/tmp/pulse_socket"**
saved the .profile

exited container

Used ContainerBox to configure sound and the 1st attempt just applied:

**ContainerBox config sound cn1 pa_enable**

Rebooted CN1 container

Logged into the XFCE desktop (in the container & logged back in) after login the Sound Icon on the XFCE desktop was _finally active_.   

I played some Youtube music video and the audio bar was moving indicating sound was being seen but I was not hearing it.

Then I wondered about whether i had to also configure the 2nd "enable" option also:

**ContainerBox config sound cn1 snd_enable**

Rebooted the Container again.

Logged into the XFCE desktop (in the container & logged back in) after login the Sound Icon on the XFCE desktop was active.   

I played some Youtube music video and the audio bar was moving indicating sound **and I was hearing the music also!**

From what I thought about Pulseaudio if you used the socket method all the communication was thru the socket to the pulseaudio "server".    I did not think you needed to pass the "sound cards" from the host to the container ?  But in my use case here it seems I do have to configure both!

**ContainerBox config sound cn1 pa_enable**  
**ContainerBox config sound cn1 snd_enable**

**Comment by AlexandreDey** [comment]
Oh yeah, forgot to mention that you have to set the PULSE_SERVER variable inside the container. Didn't did it automatically because it is user dependent so I would have to configure it for every user inside the container.

It's strange that you need both the pulse socket and the sound card, didn't need when I tested ... 

Another possibility would be to passthrough the sound card and setup pulseaudio inside the container, but it might come with a slight security concern (exposing physical devices), and also I still have a few things to learn about sound system in Linux so there might be more efficient ways to do this ;)

**Comment by bmullan** [comment]
Well I've been making changes alot so I will repeat this all again.   Like
you, I would think I should only need the 1st "pa_enable" and not have to
add the "snd_enable".

I'll retry everything again.

**Comment by bmullan** [comment]
Okay...  

ContainerBox config cn1 snd_disable

then rebooted container

and I still had audio in the container...  cool !

**Comment by bmullan** [comment]
Alexandre

I cut & pasted your README file into a LibreWriter doc and did some editing to add some of the information I learned from installing this and getting it to run.

[ContainerBox ReadMe updated.pdf](https://github.com/AlexandreDey/ContainerBox/files/2250753/ContainerBox.ReadMe.updated.pdf)

Use it if it makes sense.
Brian

**Comment by AlexandreDey** [comment]
Thanks for the help!

I was a bit busy the last few weeks, I have some time now to continue ContainerBox. First step is the documentation, and thanks for the effort, it can be useful !
The GUI will also be introduced within the next few weeks, I hope. Once that is done, the first "release candidate" will be branched and I will also introduce a new project that will involve ContainerBox :)

**Comment by bmullan** [comment]
Will or does Container box work with DNAP LXD also?

I tried it but I think the path to LXC is different with SNAP LXD.

Also, for what I wrote I can send you the LibreWriter file instead if you
need it.

**Comment by bmullan** [comment]
updated the PDF with instructions for how to install ContainerBox for use with SNAP LXD

see attached.

[ContainerBox ReadMe updated.pdf](https://github.com/AlexandreDey/ContainerBox/files/2258706/ContainerBox.ReadMe.updated.pdf)

**Comment by bmullan** [comment]
updated the PDF with instructions for how to install ContainerBox for use with SNAP LXD

see attached.
[ContainerBox ReadMe updated.pdf](https://github.com/AlexandreDey/ContainerBox/files/2259642/ContainerBox.ReadMe.updated.pdf)

**Comment by bmullan** [comment]
with Alexandre's new code the need to manually set PULSE_SERVER is no longer required as the containerbox profile does that for us now.

thanks Alexandre !!
