### ISSUE TITLE
Does or will ContainerBox utilize the LXD feature for "Proxy Device"

### ISSUE THREAD

**Issue by bmullan** [AlexandreDey/ContainerBox#8]
This may be a dumb question but thought I'd ask.

I think that the _Proxy Device feature_ is relatively recent but for Sound & Video does or will ContainerBox be able to utilize it ?

https://lxd.readthedocs.io/en/latest/api-extensions/#proxy

Brian

**Comment by AlexandreDey** [comment]
Thanks for pointing it out ! It's definitely something that I will look into (it should be better than just passing the socket file). As it can be used for proxying Unix socket, I will probably default to that instead (in the coming weeks)

**Comment by bmullan** [comment]
awesome Alexandre... I'm anxious to try the new code.

Just a reminder for a bit more info in the README for new comers to ContainerBox regarding our discussion in the "remaining" issue:

https://github.com/AlexandreDey/ContainerBox/issues/7#issuecomment-405090386

Particularly the need for the user setting the PULSE_SERVER to point to the socket.

export PULSE_SERVER="/tmp/pulse_socket"

**Comment by AlexandreDey** [comment]
As of commit 262750091b480136416cb7fe20a9a0f9658d0927 PULSE_SERVER is set in /etc/profile, so it's automatic now ;)

**Comment by bmullan** [comment]
great ... thanks.

That way no one can fail because they forgot to set it manually
